---
- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: "{{ service_enabled }}"
    use: systemd
  register: enable_service
  retries: 10
  until: enable_service is success

- name: Set service state
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    use: systemd
  register: set_service_state
  retries: 10
  until: set_service_state is success
